MAX_CONNECTION = 5
DEFAULT_PORT = 1234
DEFAULT_HOST = "0.0.0.0"
RECEIVE_SIZE = 1024
NEW_LINE = "\n"
SPACE = " "
REQUEST_LINES_COUNT = 2
NOT_FOUND_ASWER = "not_found"

CREATE_TASK_REQUEST = "CREATE"
GET_STATUS_REQUEST = "STATUS"
GET_RESULT_REQUEST = "GET"

ALL_ALLOWED_REQUESTS = [
    CREATE_TASK_REQUEST,
    GET_STATUS_REQUEST,
    GET_RESULT_REQUEST,
]

TASK_REVERSE_COMMAND = "REVERSE"
TASK_CHANGE_LETTERS_COMMAND = "CHANGE_LETTERS"

STATUS_NEW = "NEW"
STATUS_WORKING = "WORKING"
STATUS_COMPLETE = "COMPLETE"
